### ISSUE TITLE
Content: Dropdown selected value not synced

### ISSUE THREAD

**Issue by maarten-kieft** [KevinJump/uSync3.0#185]
Hi Kevin,

First: Good tool! Its a live safer to sync content created by developers. Your work is much appreciated here!

The bug we currently have is that the selected value from a dropdown is not synced. So if we selected a value from a dropdown (with custom defined values), save it. Copy the unsync files to a different server, run the import, it will set the value of that dropdown to empty. 

Steps to reproduce:

1. Create a new drop down data datatype with some values
2. Use it in a document type and select one of the values and save it
3. Run an import on a different machine.
4. The value of the dropdown is empty 

Additional information:
When I look at the usync files it has saved this information:
"buttonlistItemIcon": "7513", so the id of the value which I selected. This id matches the id of the value in the database in the table cmsDataTypePreValue. When I look in the database of the target server it exists there as well.

**Comment by KevinJump** [comment]
Hi

there are a couple of issues that have been fixed recently (#175 and #176) that i think fix this issue, but they are not in the main uSync release yet. 

if you update the version of uSync.Core you are using to v6.0.6 then you will get these two fixes and you might see a fix to this (you would have to resync everything i think)

**Comment by maarten-kieft** [comment]
Hi Kevin,

Sorry that I didn't mention it, but I'm using the latest versions:

usync: 4.0.5
usync.contentEdition: 4.1.2
usync.contentMappers 4.1.2
usync.Core: 6.0.6

So those 2 fixes didn't help? or they are not in v 6.0.6 ?

**Comment by KevinJump** [comment]
:( - I will have to take another look

**Comment by maarten-kieft** [comment]
Can I provide additional information to make the search easier?

**Comment by JohnCodeBear** [comment]
It seems this issue has not been yet fixed, i have exactly the same problem.
*also using all the latest versions.

**Comment by KevinJump** [comment]
Arrrgggg ! (sorry needed to vent - also most of this is for my own notes. ) 

**See the bottom bit for a possible solution before a code fix is issued**

I think i have worked out what needs fixing - the two fixes above fix the datatype and moving things around in the list, but content doesn't actually store the internal datatype values - rather the resultant values, 

so for example a set of prevalues : 

```
  <PreValues>
    <PreValue Id="21" Alias="0"><![CDATA[£]]></PreValue>
    <PreValue Id="20" Alias="1"><![CDATA[€]]></PreValue>
    <PreValue Id="22" Alias="2"><![CDATA[$]]></PreValue>
    <PreValue Id="23" Alias="3"><![CDATA[DKK]]></PreValue>
  </PreValues>
```

the content item will store : 
```<![CDATA[€]]>```

but for historical reasons, we map that value back so in usync it becomes : 
```<![CDATA[1]]>```

however add a new item or change the order of the list and those alias values also change - so the item value when imported back in by uSync is now pointing at something else. 

"just stop doing the mapping" i hear you say - well we can except ...

_as of v7.12.2_ 

* Dropdowns and checkboxes store the value 
* Radio button Lists - don't store the value - they store the alias - so we still need to map them somehow.
_(it might be that changing doesn't break radio button lists more then they are already broken)_

to fix this: 
- [x] I need to confirm how these values are stored in each version of umbraco from v7.6 onwards and work out if there is a breaking change and at what version it happens.
- [x] need to confirm that removing the dataTypeValue mapper doesn't break anything else (i think it is only lists that use it - but have to confirm) 

**but finally some possibly good news 🎉** 

the outcome of this may be to simply disable the content mappers for dropdowns, checkboxes etc. and this can be done in the uSyncCore.Config file. 

commenting out the following lines from uSyncCore.Config might be enough to fix this issue. 

```
    <uSyncContentMapping Alias="Umbraco.DropDownList" Mapping="DataType" />
    <uSyncContentMapping Alias="Umbraco.DropDown" Mapping="DataType" />
    <uSyncContentMapping Alias="Umbraco.DropDownMultiple" Mapping="DataType" />
    <uSyncContentMapping Alias="Umbraco.CheckBoxList" Mapping="DataType" />
```

You will need to restart the site(s) after this change, and do a content export / import (to get the content without the mapped ids in it).

**Comment by maarten-kieft** [comment]
Hi Kevin,

Thanks for the update. The proposed solution does seem to be a winner if your logic is correct. I do see that you already created a commit as well. Just wanted to let you know that the effort is appreciated!! I will try the fix later by applying the config changes.

Maarten

**Comment by KevinJump** [comment]
update : this doesn't quite work. 

even though the value is stored in the content you have to set the alias for the content to actually be set - so we need to have a half mapper that maps on import but leaves alone on export .

**Comment by KevinJump** [comment]
OK - so hopefully uSync.Core v6.0.7 (no published on nuget) should fix this 🤞

**Comment by maarten-kieft** [comment]
I don't want to scream it out loud yet, but I just did a full export/import with v6.0.7 and the dropdowns still have a value ..

**Comment by KevinJump** [comment]
good thing? bad thing ?

**Comment by maarten-kieft** [comment]
Good :) Previously the dropdown was empty again after an import..  But since I never could get the finger on how to reproduce it precisely, Im not 100% sure its resolved.

**Comment by maarten-kieft** [comment]
Bad news, I noticed that other drop downs where empty again. The usync config is set:

descendingSlant ![CDATA[1]] /descendingSlant

When I perform an full import, it remains blank:

![image](https://user-images.githubusercontent.com/23722841/45619536-e9231600-ba79-11e8-8b0e-e8cb8cb8c3c4.png)

**Comment by ltctech** [comment]
I'm currently working with Umbraco 7.10.4 and am considering upgrading to 7.12.3. My concern is that uSync will stop working correctly. You mentioned that 7.12.2 stores values differently. Does uSync already account for that or not? Are there other compatibility issues?

I use drop downs, checkbox lists, and radio button lists all over hence my concern.

**Comment by ltctech** [comment]
Upgraded to 7.12.3 tonight. Using latest version of uSync published today. Export exports the string prevalue. Import is unable to map it even though the actual DropDown.Flexible didn't change and it's on the same instance of Umbraco.

**Comment by KevinJump** [comment]
Yes - it looks like it was setting the value rather then the ID on reimport , i have patched this, and will build a new release for it.

**Comment by KevinJump** [comment]
This is fixed (hopefully) in the new 4.0.9/6.0.9 release 

if you are using nuget you can just update your uSync.Core package to 6.0.9 - the other packages have only been updated to reflect the dependency version change.

**Comment by ltctech** [comment]
Yep, that fixed it for me. Thanks.

**Comment by Swimburger** [comment]
Thank you for fixing this, it was bugging us for a while. Cheerz!
