### ISSUE TITLE
V4.0.10 Missing method in Umbraco 7.15 release

### ISSUE THREAD

**Issue by ReVoid** [KevinJump/uSync3.0#223]
Hello. 

Updated to Umbraco 7.15 (via NuGet) today and uSync throws YSOD now, with missing method:
`IUmbracoEntityUmbraco.Core.Services.IEntityService.GetByKey(System.Guid, Boolean)`

I looked Umbraco 7.15 source code and...yep, there is no` GetByKey(System.Guid, Boolean)` method anymore :( 

Looks like it needs another implementation :(

uSync 4.0.10 and uSync.Core 6.0.11

**Comment by KevinJump** [comment]
Thanks for reporting. 

This isn't marked as a breaking change in 7.15 😢 

also, they have removed the optional parameter - which I think changed the signature of elements not using it - we don't actually call GetByKey with a boolean parameter set, but I think because it's an optional parameter that has been removed the reference has gone even when you don't call it :(

so we are failing here   https://github.com/KevinJump/uSync/blob/v4_master/Jumoo.uSync.Core/Serializers/MacroSerializer.cs#L54 

I am going to log an issue in umbraco and see if we can do anything less drastic than recompile the whole usync project against 7.15 (because we are currently very backward compatable!)

**Comment by KevinJump** [comment]
doesn't look like the underlying issue is going to get fixed quickly (and it will always mean a broken 7.15.0 even if it does). 

so looking at some workarounds, possibly calling other entity service methods and munging results.

**Comment by KevinJump** [comment]
Fixed in 4.0.12 release of uSync

**Comment by DempseySbaiz** [comment]
Hey Kevin,

I think there is still an issue with Umbraco 7.15.0 and your fix.
I can't export  any datatypes or content types since the upgrade, it gives me the following error:

> Failed to save dt - nc - bericht - System.NotSupportedException: The passed in type is not supported
>    at Umbraco.Core.Services.EntityService.<>c__26`1.<GetAll>b__26_0()
>    at Umbraco.Core.Mandate.That[TException](Boolean condition, Func`1 defer)
>    at Umbraco.Core.Services.EntityService.GetAll[T](Int32[] ids)
>    at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.GetEntityPath(IUmbracoEntity item)
>    at Jumoo.uSync.BackOffice.Handlers.DataTypeHandler.ExportToDisk(IDataTypeDefinition item, String folder)

So it fails on the GetAll function that you changed in the last uSync release.
Could you check this out please? Thanks!

**Comment by KevinJump** [comment]
grrr arrg, thought i had caught that one :( -

**Comment by KevinJump** [comment]
OK, Lets try that again, - updated the parent Lookups, and checked we were calling the right version of GetAll where we have to. 

In release 4.0.13 / 6.0.13

**Comment by ReVoid** [comment]
@KevinJump I'll try new version today with 7.14 and then with 7.15 to be sure in backward compitibility.

Thanks, Kevin!
