### ISSUE TITLE
usync.once

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#29]
new version is missing uSync.Once. 

usync looks for the presence of a usync.once file in the root, if it exists it runs through the import and then creates a usync.locked file.

when a usync.locked file exists no usync runs will occur. 

not complex :) but needs to be added back.

**Comment by dgg** [comment]
does the usync.once needs to live under /usync or under /usync/data for artifacts to be synchronized?

**Comment by KevinJump** [comment]
well its not there at the moment, but when this code is added - it will be under usync/data

**Comment by Vrijdagonline** [comment]
Thanks for implementing this Kevin!

**Comment by dgg** [comment]
This is not working for me....
I place a `usync.once` file under _\usync\data_ but when the application starts nothing happens: the artifacts are not created and the file is not renamed.

uSync.BackOffice 3.1.2.740

Is there something I am missing?

**Comment by KevinJump** [comment]
yeah, thats me 

Just checked and i missed a stupid thing in not mapping one of the file paths, properly, I've actually tested it this time, and I will roll it up into a release today. 

I just need to check a couple of other, queries that may or may not be issues so i don't go around releasing 15 versions. 

Kevin

**Comment by dgg** [comment]
Awesome, I'll keep and eye on the new release...

Thanks!

**Comment by KevinJump** [comment]
Hi, this is fixed in uSync 3.1.3.740 - Released now.

**Comment by dgg** [comment]
Hi Kevin,

I must be doing something bad because it still does not work for me.
- The target environment (the one we want to import artifacts once) has this configuration:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<uSyncBackOfficeSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Import>false</Import>
    <ExportAtStartup>false</ExportAtStartup>
    <ExportOnSave>false</ExportOnSave>
    <WatchForFileChanges>false</WatchForFileChanges>
    <ArchiveVersions>false</ArchiveVersions>
    <Folder>~/uSync/data/</Folder>
    <ArchiveFolder>~/uSync/Archive/</ArchiveFolder>
    <BackupFolder>~/uSync/Backup/</BackupFolder>
    <MaxArchiveVersionCount>0</MaxArchiveVersionCount>
    <Handlers>
        <!- ...-->
    </Handlers>
</uSyncBackOfficeSettings>
```
- I copy the whole _/data_ folder from the source environment to the target environment
- Under the _/data_ folder in the target environment, there is an `uSync.once` file
- When the target application starts, nothing happens: the file is not renamed and the artifacts are not imported.
- If I manually click the dashboard button, the artifacts get created, but the idea is to not have to do that manual step.

In the "old days" (2.4) I had a similar configuration in the target environment (basically a _no_op_ in uSync terms) and, at the time of deploying new artifacts, place the `usync.once` under _/usync_ (no _/data_ sub-folder in that version) and have all my artifacts imported the first time the app starts and the file would get renamed to `usync.stop`.
Shouldn't it work the same in the new version?

**Comment by KevinJump** [comment]
Hi 

I think it's that you need to have Import set to true, so that the import happens on application start.

**Comment by dgg** [comment]
If `<Import>` is set to _true_... what is the point of the `.once` file? The artifacts are going to be imported every time the app starts. The file is not needed.

I believe the `.once` file should override the `<Import>` just as it used to be.

**Comment by KevinJump** [comment]
wait there i'll go check........ No - this has always been the way, :disappointed: 

`Import` is true so that the import process gets kicked off every app start, **but** it only actually does anything there isn't a `usync.stop` file stopping it. 

So with the `.once` file - import runs, no `.stop` so runs through at end `.once` is renamed to `.stop` for next time. 

it worked like this with the old version difference was `import` was called `read` but it had to be true for the once/stop stuff to happen.

**Comment by Vrijdagonline** [comment]
Agree. This is working perfectly fine. Just like it did in the old days ;)
I for sure love this functionality for deployments.

**Comment by dgg** [comment]
You both are absolutely right and I could not be more wrong! :$

In the old configuration we have the configuration set to read: `<usync read="true" />`.
So, of course it does work and the `.stop` will prevent importing the next time the app starts.

Thanks a lot for the help and the awesome product.
